### PR TITLE
[openwrt] Add support for EAP-PEAP

### PR DESCRIPTION
**Pull request by masap**
This patch adds support for EAP-PEAP.
And adds support for authentication method for EAP-TTLS and EAP-PEAP.

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
Don't we have to update the docs?

**Comment by masap** [comment]
> Don't we have to update the docs?

I want to finish this PR first. Could you please make an issue about this ?

**Comment by masap** [comment]
Rebased.

**Review by nemesisdesign — COMMENTED** [review]
> > Don't we have to update the docs?
> 
> I want to finish this PR first. Could you please make an issue about this ?

Docs and tests are considered parts of the patch, without any of these the patch is incomplete. If you can't do it we'll take care of it once we have time.

**Comment by masap** [comment]
> Docs and tests are considered parts of the patch, without any of these the patch is incomplete.

Fixed.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
@masap, after merging the WPA3 changes and other PRs some conflicts appeared, please can you update this PR by rebasing it on the latest master and fix the conflicts?

**Comment by masap** [comment]
Fixed conflicts.

**Pull request merged**
