### PR TITLE
[feature] Add options username and password to interface settings in the OpenWRT backend

### PR DESCRIPTION
**Pull request by okraits**
These are useful for protocols like ppp, pppoe, pppoa, etc.:

https://wiki.openwrt.org/doc/uci/network#protocol_ppp_ppp_over_modem

### CODE REVIEW

**Comment by okraits** [comment]
@nemesisdesign You mean that the properties `username` and `password` should only be available if there's a property `proto` with its value being one of `ppp`, `pppoe`, `pppoa`, `3g`, `qmi`, `ncm`, `wwan`, `pptp`, `6in4`, `aiccu` or `l2tp`? (According to the OpenWRT wiki)

Then the question would be how to do that (in the schema I guess) :-) For bridge interfaces I see that `allOf` is being used in the schema.

**Comment by nemesisdesign** [comment]
@okraits see here: https://github.com/openwisp/netjsonconfig/blob/master/netjsonconfig/schema.py#L933-L947
This customization would have to be defined in the openwrt schema though (as you're doing now) because it's OpenWRT specific.

**Comment by okraits** [comment]
@nemesisdesign schema modification done, but I need to update the docs.

**Comment by okraits** [comment]
Current status: I will need help from @nemesisdesign to fix the build errors. We'll continue to work on this in August.

**Comment by kkreitmair** [comment]
I'm a work colleague of @okraits. I will try to continue/finish this pr.
I rebased the branch to be more up to date.
My next step will be to add the tests.

**Comment by kkreitmair** [comment]
I have added the test, but a problem has arisen.
The test [test_parse_custom_proto](https://github.com/openwisp/netjsonconfig/blob/master/tests/openwrt/test_interfaces.py#L600) now fails, because the tested interface is of the new added **dialup** interface type.

Should i change the interface specification of the test _test_parse_custom_proto_ or does this test become obsolete?
Maybe anyone has another solution.

**Comment by kkreitmair** [comment]
FYI:
I think I'll sqash my commits together when the PR is finished.

**Comment by kkreitmair** [comment]
> Other notes:
> 
>     * can you ensure the author of your commits matches your email on github (or viceversa) so that you get the deserved authorship?

Thank you for the hint @nemesisdesign. I added the email address to my account.

I also added the change log note and updated the test.
If you consider the changes to be okay, I'll sqash my commits.

**Comment by kkreitmair** [comment]
> > > Other notes:
> > > ```
> > > * can you ensure the author of your commits matches your email on github (or viceversa) so that you get the deserved authorship?
> > > ```
> > 
> > 
> > Thank you for the hint @nemesisdesign. I added the email address to my account.
> > I also added the change log note and updated the test.
> > If you consider the changes to be okay, I'll sqash my commits.
> 
> Thanks, the changes look good, please proceed with the squash, I will do a final round of testing and double check then.

Thank you for the review.
I decided to fixup the commits, because the resulting commit log message history of squashing would have made no sense.

**Pull request merged**
